name: flutter3
description: Flutter 3 Tutorial

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  #flutter_localizations:
    #sdk: flutter
  #responsive layout for different size device_simulator
  responsive_framework: ^0.2.0
  #Splash page
  #splash_screen_view: ^3.0.0
  #Localization
  easy_localization: ^3.0.1
  #Provider
  provider: ^6.0.3
  #Dio
  dio: ^4.0.6
  http: ^0.13.4
  html: ^0.15.0
  # Map Locations
  google_maps_flutter: ^2.1.0
  flutter_google_places: ^0.3.0
  google_maps_webservice: ^0.0.19
  location: ^4.4.0
  location_web: ^3.1.1
  map: ^1.3.1
  cached_network_image: ^3.2.1
  #database
  postgres: ^2.4.5
  #path
  path: ^1.8.1
  #search bar
  search_widget: ^1.0.2
  #image_picker
  image_picker: ^0.8.5+3
  #Load, resize & save image to Server
  image: ^3.2.0
  #modal_bottom_sheet Awsome UI
  modal_bottom_sheet: ^2.1.0
  #Text Animation
  animated_text_kit: ^4.2.2
  #Clay containers
  clay_containers: ^0.3.2
  #Dropdown list
  flutter_dropdown: ^1.0.1+hotfix.1
  #Icons
  carbon_icons: ^0.0.1+2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - lib/src/lang/